-- Insert more members with family associations (continuation)
INSERT INTO public.members (name, email, gender, phone, address, department, baptized, family_id)
SELECT 
  m.name,
  NULLIF(m.email, '') as email,
  NULLIF(m.gender, '') as gender,
  NULLIF(m.phone, '') as phone,
  NULLIF(m.address, '') as address,
  NULLIF(m.department, '') as department,
  CASE WHEN m.baptized = 'Yes' THEN true ELSE false END as baptized,
  f.id as family_id
FROM (VALUES
  ('Pu Lian Za Thang', '', 'Male', '', '5815 Rowanberry Dr. Elkridge MD 21075', 'Member', 'Yes', 'Pu Lian Za Thang'),
  ('Pi Mah Za Sung', '', 'Female', '', '5815 Rowanberry Dr. Elkridge MD 21075', 'Member', 'Yes', 'Pu Lian Za Thang'),
  ('Cung Hrin Lian', '', 'Male', '', '5815 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Lian Za Thang'),
  ('Nun Dim Sung', '', 'Female', '', '5815 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Lian Za Thang'),
  ('Ral Cung Lian', '', 'Male', '', '5815 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Lian Za Thang'),
  ('Pu Sui Thawng', '', 'Male', '', '5829 Rowanberry Dr. Elkridge MD 21075', 'Member', 'Yes', 'Pu Sui Thawng'),
  ('Pi Dawt Tha Hlei Par', '', 'Female', '', '5829 Rowanberry Dr. Elkridge MD 21075', 'Member', 'Yes', 'Pu Sui Thawng'),
  ('Sui Dawt Sung', '', 'Female', '', '5829 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Sui Thawng'),
  ('Ngun Tin Par', '', 'Female', '', '5829 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Sui Thawng'),
  ('Denis Cunghlei Sang', '', 'Male', '', '5829 Rowanberry Dr. Elkridge MD 21075', 'Member', '', 'Pu Sui Thawng'),
  ('Pu Thawng Hlei', '', 'Male', '', '3022 Oak Green Ct Apt A Ellicott City, MD. 21043', 'Member', 'Yes', 'Pu Thawng Hlei'),
  ('Pi Van Tha Hlei', '', 'Female', '', '3022 Oak Green Ct Apt A Ellicott City, MD. 21043', 'Member', 'Yes', 'Pu Thawng Hlei'),
  ('En Di', '', 'Male', '', '3022 Oak Green Ct Apt A Ellicott City, MD. 21043', 'Member', '', 'Pu Thawng Hlei'),
  ('Pu Maung Mang Lian Dawt', '', 'Male', '', '5815 Rowanberry Drive, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Maung Mang Lian Dawt'),
  ('Pi Bawi Min Sung', '', 'Female', '', '5815 Rowanberry Drive, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Maung Mang Lian Dawt'),
  ('Samuel Bawi Tha Cem', '', 'Male', '', '5815 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Maung Mang Lian Dawt'),
  ('Dawt Chin Sung', '', 'Female', '', '5815 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Maung Mang Lian Dawt'),
  ('Andrew Ram Lian Sang', '', 'Male', '', '5815 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Maung Mang Lian Dawt'),
  ('Pu Tanh Zin', '', 'Male', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tanh Zin'),
  ('Pi Sung Caan Tial (Khin Sung)', '', 'Female', '240-855-9773', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tanh Zin'),
  ('Hnemtha Mawi Zin', '', 'Female', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Tanh Zin'),
  ('Thet Htar Shwe Zin', '', 'Female', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Tanh Zin'),
  ('Minmyat Thant Zin', '', 'Female', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Tanh Zin'),
  ('Vanbawilian Thant Zin', '', 'Male', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Tanh Zin'),
  ('Tv. Siang Hnin Lian', '', 'Male', '', '5910 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Tv. Siang Hnin Lian'),
  ('Pu Kyi Soe', '', 'Male', '', '5914 Rowanberry Drive, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Kyi Soe'),
  ('Pi Tha Chin Sung', '', 'Female', '443-936-8390', '5914 Rowanberry Drive, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Kyi Soe'),
  ('Joseph Van Tha Bik', '', 'Male', '', '5914 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Kyi Soe'),
  ('Van Hmun Lian Bik', '', 'Male', '', '5914 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Kyi Soe'),
  ('Nancy Par Tha Bik', '', 'Female', '', '5914 Rowanberry Drive, Elkridge, MD 21075', 'Member', '', 'Pu Kyi Soe'),
  ('Pu Khang Hnin', '', 'Male', '', '5956 Rowanberry Drive,Elkridge, MD 21075', 'Member', 'Yes', 'Pu Khang Hnin'),
  ('Pi Zing Hluan Par', '', 'Female', '410-926-0239', '5956 Rowanberry Drive,Elkridge, MD 21075', 'Member', 'Yes', 'Pu Khang Hnin'),
  ('Stella Biakthasung Hnin', '', 'Female', '', '5956 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Khang Hnin'),
  ('Paul Vanbawihrin Hnin', '', 'Male', '', '5956 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Khang Hnin'),
  ('Immanuel Ni Thluai', '', 'Female', '', '5956 Rowanberry Drive,Elkridge, MD 21075', 'Member', '', 'Pu Khang Hnin'),
  ('Pu Lal Dun', '', 'Male', '', '5910 Rowanberry Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Lal Dun'),
  ('Pi Amelda Sung', '', 'Female', '240-758-4623', '5910 Rowanberry Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Lal Dun'),
  ('Hmun Lian Sang', '', 'Male', '410-603-7961', '5910 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Lal Dun'),
  ('Stanley Duh Hmun Sang', '', 'Male', '', '5910 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Lal Dun'),
  ('Pu Thawng Lian Cin', '', 'Male', '', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Thawng Lian Cin'),
  ('Pi Ayeny Zathang', '', 'Female', '667-701-9745', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Thawng Lian Cin'),
  ('Angely Iang Hlei Rem', '', 'Female', '', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Lian Cin'),
  ('Kalvin Vel Lian Sang', '', 'Male', '', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Lian Cin'),
  ('Phebe Bawi Tha Chin', '', 'Female', '', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Lian Cin'),
  ('Daniel Bawi Ro Lian', '', 'Male', '', '6012 Rowanberry Dr, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Lian Cin'),
  ('Pu Sang Ceu', '', 'Male', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', 'Yes', 'Pu Sang Ceu'),
  ('Pi Hla Hla Le', '', 'Female', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', 'Yes', 'Pu Sang Ceu'),
  ('Jeremiah Van Dawt Ceu', '', 'Male', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Sang Ceu'),
  ('David Van Hlei Ceu', '', 'Male', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Sang Ceu'),
  ('Daniel Bawi Hmun Thang', '', 'Male', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Sang Ceu'),
  ('Tv. Duh Cung Lian', '', 'Male', '', '6026 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Tv. Duh Cung Lian'),
  ('Pu Ceu Er', '', 'Male', '', '6052 Rock Glen Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Ceu Er'),
  ('Pi Iang Hlei Sung', '', 'Female', '443-374-7301', '6052 Rock Glen Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Ceu Er'),
  ('John Van Bawi Sang', '', 'Male', '443-820-8977', '6052 Rock Glen Dr, Elkridge, MD 21075', 'Member', '', 'Pu Ceu Er'),
  ('Bawi Kung Thang', '', 'Male', '', '6052 Rock Glen Dr, Elkridge, MD 21075', 'Member', '', 'Pu Ceu Er'),
  ('Ngun Za Par', '', 'Female', '', '6052 Rock Glen Dr, Elkridge, MD 21075', 'Member', '', 'Pu Ceu Er'),
  ('Pu Lian Uk', '', 'Male', '', '', 'Member', 'Yes', 'Pu Lian Uk'),
  ('Pu Cung Lian Hup', '', 'Male', '', '5964 Rowanberry Drive, Elkridge, Md 21075', 'Member', 'Yes', 'Pu Cung Lian Hup'),
  ('Pi Hnem Hlei Iang', '', 'Female', '', '5964 Rowanberry Drive, Elkridge, Md 21075', 'Member', 'Yes', 'Pu Cung Lian Hup'),
  ('Bawi Ram Ceu', '', 'Male', '', '5964 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Cung Lian Hup'),
  ('Dawt Hlei Par', '', 'Female', '', '5964 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Cung Lian Hup'),
  ('Cunglian Bawi', '', 'Male', '', '5964 Rowanberry Drive, Elkridge, Md 21075', 'Member', '', 'Pu Cung Lian Hup'),
  ('Pu Van Cung Thawng', '', 'Male', '', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Deacon', 'Yes', 'Pu Van Cung Thawng'),
  ('Pi Zung Len Thluai', '', 'Female', '', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Van Cung Thawng'),
  ('Sang Awr', '', 'Male', '410-422-7659', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Member', '', 'Pu Van Cung Thawng'),
  ('Ram Za Len Par', '', 'Female', '410-603-2729', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Member', '', 'Pu Van Cung Thawng'),
  ('Van Biak Tha', '', 'Male', '', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Member', '', 'Pu Van Cung Thawng'),
  ('Titus Ram Tha Sang', '', 'Male', '', '6251 Greenfield Rd Apt L2, Elkridge, MD 21075', 'Member', '', 'Pu Van Cung Thawng'),
  ('Pu Van Bawi Lian', '', 'Male', '443-488-0654', '6401 Norris St, Hanover, MD 21076', 'Member', 'Yes', 'Pu Van Bawi Lian'),
  ('Pi Dawt Hnem Par', '', 'Female', '443-922-5380', '6402 Norris St, Hanover, MD 21076', 'Member', 'Yes', 'Pu Van Bawi Lian'),
  ('Bawi Dawt Thang', '', 'Male', '', '6403 Norris St, Hanover, MD 21076', 'Member', '', 'Pu Van Bawi Lian'),
  ('Esther Bawitha Sung', '', 'Female', '', '6404 Norris St, Hanover, MD 21076', 'Member', '', 'Pu Van Bawi Lian'),
  ('Joseph Bawilung Tling', '', 'Male', '', '6405 Norris St, Hanover, MD 21076', 'Member', '', 'Pu Van Bawi Lian'),
  ('Biak Hmun Sang', '', 'Male', '', '6406 Norris St, Hanover, MD 21076', 'Member', '', 'Pu Van Bawi Lian'),
  ('Pu Than Hmung', '', 'Male', '', '6407 Norris St, Hanover, MD 21076', 'Member', 'Yes', 'Pu Than Hmung'),
  ('Pi Khen Thluai', '', 'Female', '', '6407 Norris St, Hanover, MD 21076', 'Member', 'Yes', 'Pu Than Hmung'),
  ('Pu Tum Kheng', '', 'Male', '240-409-9612', '6398 Woodburn Ave, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tum Kheng'),
  ('Pi Rem Cia', '', 'Female', '240-485-7668', '6398 Woodburn Ave, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tum Kheng'),
  ('Antony Sang Chin', '', 'Male', '410-300-1614', '6398 Woodburn Ave, Elkridge, MD 21075', 'Member', '', 'Pu Tum Kheng'),
  ('Linda Sui Pen', '', 'Female', '410-660-7614', '6398 Woodburn Ave, Elkridge, MD 21075', 'Member', '', 'Pu Tum Kheng'),
  ('Tv. Bawi Nawl', '', 'Male', '410-300-4989', '6398 Woodburn Ave, Elkridge, MD 21075', 'Member', '', NULL),
  ('Pu Tluang Kham', '', 'Male', '', '6001 Niagara Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tluang Kham'),
  ('Pi Ni Zi', '', 'Female', '301-741-9800', '6001 Niagara Dr, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Tluang Kham'),
  ('Sui Par Chin', '', 'Female', '240-904-1379', '6001 Niagara Dr, Elkridge, MD 21075', 'Member', '', 'Pu Tluang Kham'),
  ('Ariana Chin', '', 'Female', '', '6001 Niagara Dr, Elkridge, MD 21075', 'Member', '', 'Pu Tluang Kham'),
  ('Bawi Cung Cem', '', 'Male', '', '6001 Niagara Dr, Elkridge, MD 21075', 'Member', '', 'Pu Tluang Kham'),
  ('Pu Rum Lo Thang', '', 'Male', '', '8228 Brushyridge Rd, Apt 2D Laurel, MD 20724', 'Member', 'Yes', 'Pu Rum Lo Thang'),
  ('Pi Ngun Hlei Iang', '', 'Female', '', '8228 Brushyridge Rd, Apt 2D Laurel, MD 20724', 'Member', 'Yes', 'Pu Rum Lo Thang'),
  ('Pu Thawng Hmung', '', 'Male', '', '6560 Ducketts Lane, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Thawng Hmung'),
  ('Pi Dawt Hlei Sung (Catin Tial)', '', 'Female', '', '6560 Ducketts Lane, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Thawng Hmung'),
  ('Rose Bawi Chin Sung', '', 'Female', '', '6560 Ducketts Lane, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Hmung'),
  ('Rafael Vanceu Lian', '', 'Male', '', '6560 Ducketts Lane, Elkridge, MD 21075', 'Member', '', 'Pu Thawng Hmung'),
  ('Tv. Lian Cin Thang', '', 'Male', '', '6560 Ducketts Lane, Elkridge, MD 21075', 'Member', '', NULL),
  ('Pu Robert Thawng', '', 'Male', '', '6668 Ducketts Lane, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Robert Thawng'),
  ('Pi Bawi Sung Thawng', '', 'Female', '', '6668 Ducketts Lane, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Robert Thawng'),
  ('Haney Biak Tial', '', 'Female', '240-758-5397', '6668 Ducketts Lane, Elkridge, MD 21075', 'Member', '', 'Pu Robert Thawng'),
  ('Van Nunuk Thawng', '', 'Male', '', '6668 Ducketts Lane, Elkridge, MD 21075', 'Member', '', 'Pu Robert Thawng'),
  ('Pu Hmung Khar', '', 'Male', '', '6495 Sedgwick Street, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Hmung Khar'),
  ('Pi Par Thlia (aka) Sui Tin Men', '', 'Female', '', '6495 Sedgwick Street, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Hmung Khar'),
  ('Elyna Bawi Hnem Par', '', 'Female', '410-564-6042', '6495 Sedgwick Street, Elkridge, MD 21075', 'Member', '', 'Pu Hmung Khar'),
  ('Abinago Bawi Lian Hmung', '', 'Male', '', '6495 Sedgwick Street, Elkridge, MD 21075', 'Member', '', 'Pu Hmung Khar'),
  ('Jassie Hrang Bawi Mang', '', 'Male', '', '6495 Sedgwick Street, Elkridge, MD 21075', 'Member', '', 'Pu Hmung Khar'),
  ('Pu Cung Biak Thawng', '', 'Male', '240-671-6893', '6427 Old Highgate, Elkridge, MD 21075', 'Deacon', 'Yes', 'Pu Cung Biak Thawng'),
  ('Pi Zai Hlei Par', '', 'Female', '', '6427 Old Highgate, Elkridge, MD 21075', 'Member', 'Yes', 'Pu Cung Biak Thawng'),
  ('Biak Hnem Sung', '', 'Female', '667-274-4567', '6427 Old Highgate, Elkridge, MD 21075', 'Member', '', 'Pu Cung Biak Thawng'),
  ('David Bawi Dawt Thawng', '', 'Male', '', '6427 Old Highgate, Elkridge, MD 21075', 'Member', '', 'Pu Cung Biak Thawng'),
  ('Isaac Bawi Vel Thawng', '', 'Male', '', '6427 Old Highgate, Elkridge, MD 21075', 'Member', '', 'Pu Cung Biak Thawng')
) AS m(name, email, gender, phone, address, department, baptized, family_group)
LEFT JOIN public.families f ON f.family_name = m.family_group;