// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auztoefiuddwerfbpcpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1enRvZWZpdWRkd2VyZmJwY3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NjQwNDcsImV4cCI6MjA3NjM0MDA0N30.hQFOBZSxmtEedImOsLNoy6u_5s7EzRJ0t5klvyzXgtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});